"""Make armor nullable

Revision ID: 64201042aaa0
Revises: b20b92aa75ff
Create Date: 2022-01-20 12:30:30.657600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64201042aaa0'
down_revision = 'b20b92aa75ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'armor',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'armor',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
