"""user Id for tables

Revision ID: 3df51ab43645
Revises: 1cd9566bd74f
Create Date: 2022-04-02 12:10:42.096170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df51ab43645'
down_revision = '1cd9566bd74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'features', 'users', ['user_id'], ['id'])
    op.add_column('items', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'items', 'users', ['user_id'], ['id'])
    op.add_column('proficiencies', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'proficiencies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proficiencies', type_='foreignkey')
    op.drop_column('proficiencies', 'user_id')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'user_id')
    op.drop_constraint(None, 'features', type_='foreignkey')
    op.drop_column('features', 'user_id')
    # ### end Alembic commands ###
