"""add characters table

Revision ID: 56d1558294ff
Revises: de5f601a7754
Create Date: 2022-01-20 00:06:13.450913

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '56d1558294ff'
down_revision = 'de5f601a7754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('char_class', sa.String(
                        length=40), nullable=False),
                    sa.Column('race', sa.String(length=40), nullable=False),
                    sa.Column('background', sa.String(
                        length=40), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('level', sa.Integer(), nullable=False),
                    sa.Column('exp', sa.Integer(), nullable=False),
                    sa.Column('armor', sa.Integer(), nullable=False),
                    sa.Column('speed', sa.Integer(), nullable=False),
                    sa.Column('hp_curr', sa.Integer(), nullable=False),
                    sa.Column('hp_temp', sa.Integer(), nullable=False),
                    sa.Column('hd_curr', sa.Integer(), nullable=False),
                    sa.Column('hp_max', sa.Integer(), nullable=False),
                    sa.Column('ds_pass', sa.Integer(), nullable=False),
                    sa.Column('ds_fail', sa.Integer(), nullable=False),
                    sa.Column('strength', sa.Integer(), nullable=False),
                    sa.Column('dexterity', sa.Integer(), nullable=False),
                    sa.Column('constitution', sa.Integer(), nullable=False),
                    sa.Column('intelligence', sa.Integer(), nullable=False),
                    sa.Column('wisdom', sa.Integer(), nullable=False),
                    sa.Column('charisma', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE characters SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
