"""Campaign id nullable

Revision ID: f0e12a552969
Revises: 7a5f5e2f33ed
Create Date: 2022-03-05 16:36:02.557902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e12a552969'
down_revision = '7a5f5e2f33ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
