"""empty message

Revision ID: df83d866a953
Revises: 2bedae645449
Create Date: 2022-01-29 13:48:47.686728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df83d866a953'
down_revision = '2bedae645449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
