"""typo in image model

Revision ID: 1cd9566bd74f
Revises: 3525ff21188d
Create Date: 2022-03-07 14:30:16.776931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd9566bd74f'
down_revision = '3525ff21188d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_user_id_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_user_id_fkey', 'images', 'characters', ['user_id'], ['id'])
    # ### end Alembic commands ###
