"""rename owner col

Revision ID: 0dd7071fd052
Revises: 23a293cf871e
Create Date: 2022-03-05 16:12:17.069695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dd7071fd052'
down_revision = '23a293cf871e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('campaigns_owner_id_fkey', 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'users', ['user_id'], ['id'])
    op.drop_column('campaigns', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key('campaigns_owner_id_fkey', 'campaigns', 'users', ['owner_id'], ['id'])
    op.drop_column('campaigns', 'user_id')
    # ### end Alembic commands ###
