"""Add subclass col

Revision ID: 07e011f2c2b2
Revises: 64201042aaa0
Create Date: 2022-01-20 12:55:55.204083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e011f2c2b2'
down_revision = '64201042aaa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('sub_class', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'sub_class')
    # ### end Alembic commands ###
