"""Chars and campaigns relation

Revision ID: 7a5f5e2f33ed
Revises: 0dd7071fd052
Create Date: 2022-03-05 16:31:49.775819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5f5e2f33ed'
down_revision = '0dd7071fd052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('campaign_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'characters', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_column('characters', 'campaign_id')
    # ### end Alembic commands ###
